# Generated by Django 3.2.7 on 2021-10-03 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MFP', '0002_alter_total_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='total',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
